[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm run docs:build"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
