packages:
  - date-io-playground/
  - docs/
  - playground/
  - vuetify-io-playground/
  - vuetify-locale-playground/

catalog:
  "@nuxt/kit": ^3.12.3
  defu: ^6.1.4
  destr: ^2.0.3
  local-pkg: ^0.5.0
  pathe: ^1.1.2
  perfect-debounce: ^1.0.0
  ufo: ^1.5.3
  unconfig: ^0.3.11
  vite-plugin-vuetify: ^2.0.3
  vuetify: ^3.6.12
  "@antfu/eslint-config": ^0.43.1
  "@antfu/ni": ^0.21.10
  "@date-io/luxon": ^2.17.0
  "@fortawesome/fontawesome-svg-core": ^6.4.2
  "@fortawesome/free-solid-svg-icons": ^6.4.2
  "@fortawesome/vue-fontawesome": ^3.0.5
  "@iconify-json/carbon": ^1.1.21
  "@iconify-json/mdi": ^1.1.55
  "@mdi/js": ^7.3.67
  "@nuxt/devtools": ^1.3.9
  "@nuxt/module-builder": ^0.5.5
  "@nuxt/schema": ^3.12.3
  "@nuxt/test-utils": ^3.13.1
  "@nuxtjs/i18n": ^8.2.0
  "@parcel/watcher": ^2.3.0
  "@types/node": ^18
  "@unocss/nuxt": ^0.61.3
  bumpp: ^9.2.0
  eslint: ^8.54.0
  luxon: ^3.4.3
  nuxt: ^3.12.2
  publint: ^0.2.5
  rimraf: ^5.0.5
  sass: ^1.63.6
  typescript: ^5.3.3
  vite: ^5.0.12
  vitest: ^1.4.0
  vue-tsc: ^2.0.26
  "@date-io/date-fns": ^2.17.0
  "@date-io/date-fns-jalali": ^2.17.0
  "@date-io/dayjs": ^2.17.0
  "@date-io/hijri": ^2.17.0
  "@date-io/js-joda": ^2.17.0
  "@date-io/moment": ^2.17.0
  "@js-joda/core": ^3.2.0
  "@js-joda/locale_en-us": ^3.2.2
  "@js-joda/locale_es": ^3.2.2
  "@types/date-fns": ^2.6.0
  "@types/moment": ^2.13.0
  "@types/moment-hijri": ^2.1.0
  "@types/moment-jalaali": ^0.7.6
  date-fns: ^2.30.0
  date-fns-jalali: ^2.19.0-2
  dayjs: ^1.11.10
  moment: ^2.29.4
  moment-hijri: ^2.1.2
  moment-jalaali: 0.9.2

catalogs:
  resolutions:
    "@nuxt/kit": 3.12.3
    nuxt: 3.12.3
    vite: 5.3.3
    vue: 3.4.31
